version: "2"
services:
  league-manager-pro:
    build: ./
    volumes: 
    ports:
    command: node serve.js

  db:
    image: mysql/mysql-server:5.6
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret-root
      MYSQL_DATABASE: dbname
      MYSQL_USER: web
      MYSQL_PASSWORD: web
