version: "2.1"
services:
  nginx:
    restart: always
    build: ./configs/nginx
    ports:
      - "80:80"
    expose:
      - "80"
    links:
      - league_manager_pro_1:league_manager_pro_1
    command: service nginx start
  mysql:
    build: ./configs/database
    restart: unless-stopped
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret-root
      MYSQL_DATABASE: pro_league_manager
      MYSQL_USER: web
      MYSQL_PASSWORD: web
    healthcheck:
      test: "exit 0"
    volumes:
      - ./configs/database/1-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./configs/database/2-data.sql:/docker-entrypoint-initdb.d/2-data.sql
  league_manager_pro_1:
    build: .
    ports:
      - "3000:3000"
    environment: 
      - DB_HOST=mysql
    expose:
      - "3000"
    depends_on:
      mysql:
        condition: service_healthy
    command: bash -c "node server/bootscript-db.js && node ."